clusterName: eks-gitops-demo-prod
region: eu-west-1
vpcId: vpc-0f42646c24d9376e1

serviceAccount:
  create: false
  name: aws-load-balancer-controller

iamRoleArn: arn:aws:iam::111310799979:role/eks-gitops-demo-prod-alb-controller-role