clusterName: eks-gitops-demo-dev
region: us-east-1
vpcId: vpc-0ea2e978da3da991d

serviceAccount:
  create: false
  name: aws-load-balancer-controller

iamRoleArn: arn:aws:iam::111310799979:role/eks-gitops-demo-dev-alb-controller-role