clusterName: eks-gitops-demo-dev
region: us-east-1
vpcId: vpc-09a400da9fedf5c2d

serviceAccount:
  create: false
  name: aws-load-balancer-controller

iamRoleArn: arn:aws:iam::111310799979:role/eks-gitops-demo-dev-alb-controller-role