apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller-sa-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/ItayBracha11/gitops-platform-project.git
    targetRevision: HEAD
    path: gitops/infrastructure/alb-controller
    
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true